### ISSUE TITLE
[BUG] Could not find the plugin PluginTypes.PHONEME.ovos-g2p-plugin-heuristic-arpa

### ISSUE THREAD

**Issue by goldyfruit** [NeonGeckoCom/neon-g2p-plugin-mimic#1]
### Description

`neon-g2p-plugin-mimic` is installed into the `ovos_audio` container but I got this error when the container starts.

```
2023-08-20 14:06:24.320 - audio - ovos_plugin_manager.utils:load_plugin:145 - WARNING - Could not find the plugin PluginTypes.PHONEME.ovos-g2p-plugin-heuristic-arpa
2023-08-20 14:06:24.320 - audio - ovos_plugin_manager.g2p:create:142 - ERROR - The selected G2P plugin could not be loaded.
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
2023-08-20 14:06:24.321 - audio - ovos_plugin_manager.templates.tts:__init__:448 - ERROR - G2P plugin not loaded, there will be no mouth movements
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/templates/tts.py", line 446, in __init__
    self.g2p = OVOSG2PFactory.create(cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/g2p.py", line 139, in create
    g2p = clazz(g2p_config)
          ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by goldyfruit** [comment]
Closing as its not related to this plugin.
